### ISSUE TITLE
Line endings error in Perl script

### ISSUE THREAD

**Issue by btstromberg** [gunnarhaslinger/veeam_backup.pl#1]
The Perl script seems like it has DOS style line endings, resulting in this error when running the shell script:

./backup.sh: ./veeam_backup.pl: /usr/bin/perl^M: bad interpreter: No such file or directory

After running dos2unix on the script file it works. I am new to Github so I'm not sure how Pull requests work. Just thought I'd let you know :)

**Comment by gunnarhaslinger** [comment]
Thanks for pointing this out. Changed Line-Endings to LF.
